### ISSUE TITLE
Enable showing Chinese directly inside output files.

### ISSUE THREAD

**Issue by gary258796** [git-commit-id/git-commit-id-plugin-core#10]
### Idea
It's better to see any original text rather than text being transformed into unicode in the output files because it's more readable for us.

### Attempt
Enable to control **escapeUnicode** parameter that is send to function **saveConvert** with a new parameter we can set into class **PropertiesFileGenerator** , and then send it to method **dumpProperties** from class **PropertyManager**,  in order to show , like Chinese, directly inside generated output files.

### Expected Behavior 

When setting this new parameter into true, we can get output file with text showing directly without being transformed into unicode.

**Comment by TheSnoozer** [comment]
Thanks for your investigation & contribution; closing this since https://github.com/git-commit-id/git-commit-id-plugin-core/pull/11 was merged.
