### ISSUE TITLE
commit.committer.time is actually author time

### ISSUE THREAD

**Issue by commonquail** [git-commit-id/git-commit-id-plugin-core#82]
### Describe the bug (required)

The `commit.committer.time` property gets populated with the commit authoring time, i.e. the same value as `commit.author.time`. This happens because [both values use the same supplier](https://github.com/git-commit-id/git-commit-id-plugin-core/blob/v6.0.0-rc.6/src/main/java/pl/project13/core/GitDataProvider.java#L299-L302), which `COMMIT_COMMITTER_TIME` clearly confirms was not the intention. This error has existed since the properties' introduction in v4.0.4.

### Steps to Reproduce (required)

```sh
$ mvn package -P git-with-parent >/dev/null ; grep commit.*time target/classes/git.properties
git.commit.author.time=2019-08-25T20\:59\:43+0200
git.commit.committer.time=2019-08-25T20\:59\:43+0200
git.commit.time=2019-08-25T21\:03\:44+0200
```

with

```diff
diff --git a/pom.xml b/pom.xml
index b6fe073..3966f56 100644
--- a/pom.xml
+++ b/pom.xml
@@ -43,7 +43,7 @@
 		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
 		<java.target>1.8</java.target>
 		<!--<git-commit-id-version>2.2.5</git-commit-id-version> -->
-		<git-commit-id-version>3.0.0</git-commit-id-version>
+		<git-commit-id-version>4.0.4</git-commit-id-version>
 		<sonar.projectVersion>${project.version}-${git.branch}</sonar.projectVersion>
 	</properties>
 
```

applied to https://github.com/git-commit-id/git-commit-id-maven-debugging/commit/beef4e92e9cabd043b105a14514289f331b40bf2

**Comment by TheSnoozer** [comment]
Fix is merged, thanks again for the report and contribution. Going ahead and close.
